# For more information: https://laravel.com/docs/sail
version: "3"
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - selenium
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    echo:
        image: oanhnn/laravel-echo-server:latest
        depends_on:
            - laravel.test
            - redis
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            LARAVEL_ECHO_SERVER_AUTH_HOST: 'http://laravel.test'
            LARAVEL_ECHO_SERVER_DEBUG: 'true'
            LARAVEL_ECHO_SERVER_DB: redis
            REDIS_HOST: '${REDIS_HOST}'
            REDIS_PORT: '${REDIS_PORT}'
        networks:
            - sail
        ports:
            - '${MIX_SOCKET_PORT:-6001}:6001'
        restart: unless-stopped
        healthcheck:
            test: /usr/local/bin/health-check
            interval: 1s
            timeout: 3s
            retries: 10
    # selenium:
    #    image: 'selenium/standalone-chrome'
    #    volumes:
    #         - '/dev/shm:/dev/shm'
    #    networks:
    #        - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local
